Add Czech translation
mjakeman/extension-manager pull request #105
Opened 2022-02-09 18:19 UTC by pervoj

Czech translation is done

2022-02-09 19:46 UTC, AsciiWolf requested changes
LGTM except the one small typo, thanks!

2022-02-09 19:46 UTC, AsciiWolf commented on po/cs.po
> +msgstr "Jednoduchý správce rozšířeni GNOME Shellu"
Small typo: rozšířeni -> rozšíření

2022-02-09 19:46 UTC, AsciiWolf commented on po/cs.po
> +msgstr "Zobrazování screenshotů v seznamu rozšíření"
screenshotů -> snímků obrazovky?

2022-02-09 19:49 UTC, pervoj commented
@AsciiWolf thanks, fixed

2022-02-10 11:43 UTC, mjakeman commented
Thanks! Looks great, let's merge it

2022-02-10 11:44 UTC, merged