Add Croatian language
mjakeman/extension-manager pull request #160
Opened 2022-03-30 17:57 UTC by muzena

2022-03-31 07:09 UTC, mjakeman requested changes
Thanks for the contribution!

It all looks good to me, just one minor point about the translator-credits string.

2022-03-31 07:09 UTC, mjakeman commented on po/hr.po
> +"  gogo https://launchpad.net/~trebelnik-stefina"
In the interest of consistency, could you write this in the format: `Firstname Lastname` or `Firstname Lastname <email@website.com>` please?

2022-03-31 10:08 UTC, muzena commented
@mjakeman 
I now ok?

2022-04-05 10:27 UTC, mjakeman commented
Yes, thanks - this looks good to merge now

2022-04-05 10:27 UTC, mjakeman approved these changes

2022-04-05 10:42 UTC, merged