Create zh_TW.po
mjakeman/extension-manager pull request #199
Opened 2022-05-27 07:59 UTC by olivertzeng

2022-06-04 03:28 UTC, mjakeman requested changes
Hi, thanks for the contribution!

Everything looks good, just one issue with the translator-credits string.

2022-06-04 03:28 UTC, mjakeman commented on po/zh_TW.po
> +msgstr "Oliver Tzeng(曾嘉禾)<olivertzengolivertzeng@gmail.com>"
```suggestion
msgstr "Oliver Tzeng(曾嘉禾) <olivertzengolivertzeng@gmail.com>"
```

We need a space here for the email to be recognised properly

2022-06-04 04:17 UTC, olivertzeng commented
Hey thanks

2022-06-08 00:06 UTC, mjakeman approved these changes

2022-06-08 00:07 UTC, merged