Add Arabic Translation
mjakeman/extension-manager pull request #216
Opened 2022-06-20 11:04 UTC by ots25

2022-06-27 00:51 UTC, mjakeman requested changes
Hi, thanks for the translation - always appreciated!

There are a few minor issues here, could you accept the proposed changes? Then it should be fine to merge.

2022-06-27 00:51 UTC, mjakeman commented on po/ar.po
> +msgstr "Omar TS ots@duck.com"
This should have angle brackets '<>' around it since it is an email:
```suggestion
msgstr "Omar TS <ots@duck.com>"
```

2022-06-27 00:51 UTC, mjakeman commented on po/ar.po
> +msgstr "أدخل كلمة أساسية للبحث في "extension.gnome.org" عن امتدادات جنوم شل."
The correct URL is 'extensions' and not 'extension'. Also I'm not 100% sure, but the quotation marks here should probably be escaped with a backslash:

```suggestion
msgstr "أدخل كلمة أساسية للبحث في \"extensions.gnome.org\" عن امتدادات جنوم شل."
```

2022-06-27 02:42 UTC, ots25 commented
I certainly accept these changes, and apologize for the unintended mistakes. my greetings. بتاريخ 27‏/06‏/2022 01:52، كتب Matt Jakeman ***@***.***>:

@mjakeman requested changes on this pull request.



Hi, thanks for the translation - always appreciated!

There are a few minor issues here, could you accept the proposed changes? Then it should be fine to merge.



In po/ar.po:

> +#: data/com.mattjakeman.ExtensionManager.appdata.xml.in.in:83

+msgid "Displays user and system extensions separately"

+msgstr "يعرض امتدادات المستخدم والنظام بشكل منفصل"

+

+#: src/exm-application.c:106

+msgid "Extension Manager (Development)"

+msgstr "مدير الامتداد (تطوير)"

+

+#: src/exm-application.c:107

+msgid "Extension Manager"

+msgstr "مدير الامتداد"

+

+#. TRANSLATORS: 'Name ***@***.***>' or 'Name https://website.example'

+#: src/exm-application.c:117

+msgid "translator-credits"

+msgstr "Omar TS ***@***.***"



This should have angle brackets '<>' around it since it is an email:

⬇️ Suggested change

-msgstr "Omar TS ***@***.***"

+msgstr "Omar TS ***@***.***>"











In po/ar.po:

> +"extensions."

+msgstr "أداة بسيطة للغاية لتصفح وتنزيل وإدارة امتدادات جنوم شل "

+"."

+

+#: src/exm-application.c:124

+msgid "Project Homepage"

+msgstr "صفحة المشروع الرئيسية"

+

+#: src/exm-browse-page.blp:7

+msgid "Search for extensions"

+msgstr "بحث عن الامتدادات"

+

+#: src/exm-browse-page.blp:8

+msgid ""

+"Enter a keyword to search 'extensions.gnome.org' for GNOME Shell Extensions."

+msgstr "أدخل كلمة أساسية للبحث في "extension.gnome.org" عن امتدادات جنوم شل."



The correct URL is 'extensions' and not 'extension'. Also I'm not 100% sure, but the quotation marks here should probably be escaped with a backslash:

⬇️ Suggested change

-msgstr "أدخل كلمة أساسية للبحث في "extension.gnome.org" عن امتدادات جنوم شل."

+msgstr "أدخل كلمة أساسية للبحث في \"extensions.gnome.org\" عن امتدادات جنوم شل."







—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-06-28 02:04 UTC, mjakeman approved these changes
No worries, thanks again for the contribution!

2022-06-28 02:05 UTC, merged