po: Added Estonian translation
mjakeman/extension-manager pull request #240
Opened 2022-08-21 21:21 UTC by tenseoverflow

Added Estonian (et) translation to the project.

2022-08-31 08:15 UTC, mjakeman requested changes
Hi, thanks for the contribution!

There are a few minor issues but otherwise looks good to me.

2022-08-31 08:15 UTC, mjakeman commented on po/et.po
> +msgstr "Henri <contact@hen.ee>, 2022"
```suggestion
msgstr "Henri <contact@hen.ee>"
```

This shouldn't have a year here (as it breaks the email formatting)

2022-08-31 08:15 UTC, mjakeman commented on po/et.po
> +msgstr "Laadimine..."
```suggestion
msgstr "Laadimine…"
```

Please use the ellipsis character '…' instead of three dots.

2022-08-31 19:24 UTC, tenseoverflow commented
Thanks for your review! I've gone ahead and committed your changes.

2022-09-01 23:04 UTC, mjakeman commented
Great, thank you!

2022-09-01 23:04 UTC, mjakeman approved these changes

2022-09-01 23:06 UTC, merged