fix: move icons to gressource
mjakeman/extension-manager pull request #242
Opened 2022-08-23 14:44 UTC by 0xMRTT

Icons are currently installed in datadir, it can cause conflict with others apps (maybe they are using the same icons). So, i move icons to  `gressource`

2022-08-31 09:10 UTC, mjakeman requested changes
Thanks for working on this!

The change looks good to me - makes sense to bundle them as resources.

It seems like you've changed the formatting for `exm-rating.c`. I'm not sure if there is any change here, or if it's just been formatted by accident, but please stick to the project's coding style.

2022-08-31 09:11 UTC, 0xMRTT commented
Oh sorry, it's because I thought that I need to change something but i was wrong

2022-08-31 14:40 UTC, 0xMRTT commented
Fixed

2022-09-01 23:03 UTC, mjakeman requested changes
A few other small issues I noticed

Once fixed, could you squash this into a single commit please to keep git history tidy?

2022-09-01 23:03 UTC, mjakeman commented on src/exm-rating.c
> +}
Please don't remove the newline here as it pollutes git history. You can remove this file altogether using:

```
# Undo last commit(s) where 1 is the number of commits to undo
git reset --soft HEAD~1

# Add only the relevant files
git add src/exm.gresource.xml
git add data

# Recommit
git commit -m "..."
```

2022-09-01 23:03 UTC, mjakeman commented on src/exm.gresource.xml
> +  <gresource prefix="/com/github/GradienceTeam/Gradience/icons/scalable/actions/">
Wrong prefix :)

Should be `/com/mattjakeman/ExtensionManager/...`

2022-09-19 19:54 UTC, mjakeman approved these changes

2022-09-19 19:54 UTC, mjakeman commented
Let's get this merged for 0.4, thanks for the contribution!

2022-09-19 19:54 UTC, merged

2022-09-19 19:58 UTC, 0xMRTT commented
Thanks