Add snap support.
mjakeman/extension-manager pull request #314
Opened 2022-11-16 09:17 UTC by dingdang66686

2022-11-17 13:46 UTC, mjakeman commented
Hi, thanks for working on this!

At a high level it all looks good to me. I'll have to test this in some detail but I'm happy to keep the snap build files in-tree as an 'official' port.

One comment: could you please rename the app from `gnome-extension-manager` to simply `extension-manager`? We're not a GNOME core app so using according to the [App Naming Guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) we should avoid using 'GNOME' in the name.

2022-11-17 13:46 UTC, mjakeman requested changes

2022-11-17 17:45 UTC, Tamaraa01x commented on snap/snapcraft.yaml
> +name: gnome-extension-manager # you probably want to 'snapcraft register <name>'
- [ ]

2022-11-18 00:34 UTC, dingdang66686 commented on snap/snapcraft.yaml
> +name: gnome-extension-manager # you probably want to 'snapcraft register <name>'
I have changed that.

2022-11-18 14:27 UTC, Tamaraa01x approved these changes

2022-11-24 09:49 UTC, dingdang66686 commented
This configuration is now usable.

2022-12-11 07:07 UTC, mjakeman commented
Hi @dingdang66686, sorry for the delay in testing.

It seems snapcraft is [completely broken on the arm64 architecture](https://bugs.launchpad.net/snapcraft/+bug/1999321), at least on the two distributions I've tried it on, so I'm unable to test the snap at the moment. I'll try dig up an x86 laptop to test it with soon.

In regards to snap support, I notice you've got a package here: https://snapcraft.io/gnome-extension-manager. Did you want to continue maintaining this unofficially, or transfer ownership and have it maintained upstream (as part of this PR)?

2022-12-12 02:04 UTC, dingdang66686 commented
I have to mention that this application doesn't work in sandboxed mode. When apparmor is enabled, the dbus message is blocked. I have checked the official documentation but without luck.

2022-12-12 04:00 UTC, dingdang66686 commented
https://1drv.ms/u/s!AjQ7y8jf_bBFmIRY_zOSIdzXAMD-6w?e=CfKWrG @mjakeman Test this snap on your arm64 device.

2023-01-22 06:11 UTC, mjakeman commented
Hi @dingdang66686,

I've finally had the chance to review and test this. I've fixed the issues I was having with arm snaps by using an Ubuntu VM image. On the whole, the package looks good.

There are a few points: 
 - Could you add 'arm64' to the supported architectures
 - The snap is currently in devmode. There's nothing preventing extension-manager from working within a sandbox; I believe it should be possible to use the [`dbus`](https://forum.snapcraft.io/t/the-dbus-interface/2038) interface to make it confined again?

2023-01-22 06:12 UTC, mjakeman requested changes
See above

2023-01-27 12:02 UTC, mjakeman commented
Unfortunately, AppArmor prevents the app from using dbus, meaning that it can't install anything now.

<img width="495" alt="image" src="https://user-images.githubusercontent.com/12368711/215081490-fac07581-71c9-4465-ae33-83d8249ebd6c.png">

There isn't anything stopping the app from working with confinement (by design), so I'd ask that the snap file declares the proper permissions so we can use strict confinement. Maybe this will help: https://forum.snapcraft.io/t/the-dbus-interface/2038

2023-01-28 11:22 UTC, dingdang66686 commented
As the document says, the dbus interface is only for communications between snaps. I don't think this will help.

2023-02-12 07:38 UTC, mjakeman commented
> As the document says, the dbus interface is only for communications between snaps. I don't think this will help.

Yep, you're absolutely right. I misread that, apologies.

I've spent a lot of time looking at snap interfaces and how we can work around this for confinement purposes. Unfortunately, if there is a solution it does not look trivial (which is a bit odd, given that DBus is the primary means of achieving confinement under flatpak).

Thanks for your patience with this PR - I'm happy to take this as-is in time for the 0.4.1 release, and we can look at tightening things up later on.

2023-02-12 07:39 UTC, mjakeman approved these changes

2023-02-12 07:41 UTC, merged

2023-02-12 09:00 UTC, mjakeman commented
Hi @dingdang66686, I'm looking at making a new release of Extension Manager in the next week or so. I'm happy to take ownership of the snap package and handle releases if you're agreeable?

2023-02-12 12:43 UTC, dingdang66686 commented
I'm glad to do so. 😁

2023-02-12 12:46 UTC, dingdang66686 commented
Maybe we should ask snap developers to add a new slot/plug for gnome extension managing.

2023-02-12 12:59 UTC, mjakeman commented
Great! I've opened a request: https://forum.snapcraft.io/t/transfer-ownership-of-extension-manager-and-rename-package/33870?u=mjakeman

> Maybe we should ask snap developers to add a new slot/plug for gnome extension managing.

I think that's a good idea. Let's publish v0.4.1 using classic confinement so we have a working version out in the wild. We can ask for either a session-dbus interface, or maybe some kind of gnome-specific plug that whitelists `org.gnome.Shell.Extensions`?

2023-02-13 01:46 UTC, dingdang66686 commented
You can register a different snap named extension-manager. Then I will close my snap.