po: Add Norwegian (bokmal) Translation
mjakeman/extension-manager pull request #95
Opened 2022-02-02 15:46 UTC by jeblad

The string “Localised into seven languages” seems odd…

2022-02-04 04:21 UTC, mjakeman commented
Thank you, much appreciated!

> The string “Localised into seven languages” seems odd…

Yeah, this is part of the changelog for the 0.2.0 release rather than the actual app. I sort of regret adding it in, because we're well over seven languages now and every new translation needs to translate it. Might have to rethink whether we translate release notes down the line (or rather, maybe only keep the past three releases?).

Anyhow, this looks good to me. Let's merge.

2022-02-04 04:24 UTC, mjakeman requested changes
Just noticed an issue with `translator-credits`. One minor change, and then it's good to merge :)

2022-02-04 04:24 UTC, mjakeman commented on po/nb.po
> +msgstr "kreditering av oversettere"
Ah actually, just noticed this. This should be substituted with your name so you are credited in the about dialog whenever someone uses the translation. So for example, you might put:

`John Doe <email@website.com>`

If you don't want to provide an email, then simply `Firstname Lastname` is fine.

2022-02-21 10:53 UTC, mjakeman approved these changes

2022-02-21 10:54 UTC, merged

2022-02-21 21:35 UTC, jeblad commented
Sorry, forgot to check this after it was submitted! ;)